// Demo Mode - Dados fictícios realistas para demonstração ACR
// Activar com VITE_SEED_ENABLED=true no .env

import { addDays, subDays, format } from "date-fns";
import type { EmailThread, EmailMessage, EmailAccount, EmailAttachment } from "@/types/email";
import type { Client, Contact, ActivityLogEntry, Comment, WorkItemLink } from "@/types/clients";
import type { TaskWithRelations } from "@/types/tasks";

// ============================================
// HELPER: IDs determinísticos para demo
// ============================================
const DEMO_IDS = {
  account: "demo-account-001",
  // Clients
  client1: "demo-client-001",
  client2: "demo-client-002",
  client3: "demo-client-003",
  client4: "demo-client-004",
  // Contacts
  contact1: "demo-contact-001",
  contact2: "demo-contact-002",
  contact3: "demo-contact-003",
  contact4: "demo-contact-004",
  contact5: "demo-contact-005",
  // Threads
  thread1: "demo-thread-001",
  thread2: "demo-thread-002",
  thread3: "demo-thread-003",
  thread4: "demo-thread-004",
  thread5: "demo-thread-005",
  // Tasks
  task1: "demo-task-001",
  task2: "demo-task-002",
  task3: "demo-task-003",
  task4: "demo-task-004",
  task5: "demo-task-005",
  task6: "demo-task-006",
  task7: "demo-task-007",
  task8: "demo-task-008",
  task9: "demo-task-009",
  task10: "demo-task-010",
  // Obrigações
  obrigacao1: "demo-obrigacao-001",
  obrigacao2: "demo-obrigacao-002",
  obrigacao3: "demo-obrigacao-003",
  obrigacao4: "demo-obrigacao-004",
  obrigacao5: "demo-obrigacao-005",
  obrigacao6: "demo-obrigacao-006",
  obrigacao7: "demo-obrigacao-007",
  obrigacao8: "demo-obrigacao-008",
  obrigacao9: "demo-obrigacao-009",
  obrigacao10: "demo-obrigacao-010",
  obrigacao11: "demo-obrigacao-011",
  obrigacao12: "demo-obrigacao-012",
  obrigacao13: "demo-obrigacao-013",
  obrigacao14: "demo-obrigacao-014",
  obrigacao15: "demo-obrigacao-015",
  // Work Item Links
  workItemLink1: "demo-wil-001",
  workItemLink2: "demo-wil-002",
  workItemLink3: "demo-wil-003",
} as const;

const now = new Date();

// ============================================
// CONTA DE EMAIL DEMO
// ============================================
export const demoEmailAccount: EmailAccount = {
  id: DEMO_IDS.account,
  provider: "gmail",
  display_name: "Ana Rodrigues",
  email_address: "ana.rodrigues@acr-contabilidade.pt",
  oauth_provider: "google",
  oauth_expiry: addDays(now, 30).toISOString(),
  active: true,
  last_sync_at: now.toISOString(),
  sync_status: "idle",
  sync_error: null,
  owner_id: "demo-user-id",
  tenant_id: "demo-user-id",
  created_at: subDays(now, 90).toISOString(),
  updated_at: now.toISOString(),
};

// ============================================
// CLIENTES DEMO (4 empresas realistas)
// ============================================
export const demoClients: Client[] = [
  {
    id: DEMO_IDS.client1,
    name: "Alfa Indústria Lda",
    vat_number: "PT509123456",
    email: "geral@alfaindustria.pt",
    phone: "+351 21 456 7890",
    address: "Zona Industrial de Sintra, Lote 42, 2710-089 Sintra",
    notes: "Cliente desde 2019. Empresa de fabrico de componentes metálicos. Faturação anual ~€2.5M.",
    legacy_cliente_id: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 730).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.client2,
    name: "Beta Consulting S.A.",
    vat_number: "PT510987654",
    email: "admin@betaconsulting.pt",
    phone: "+351 21 789 0123",
    address: "Av. da República, 50 - 8º, 1050-196 Lisboa",
    notes: "Consultora de gestão. Regime trimestral de IVA. Várias operações intracomunitárias.",
    legacy_cliente_id: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 500).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.client3,
    name: "Gama Restauração Unip. Lda",
    vat_number: "PT511234567",
    email: "contabilidade@gamarestauracao.pt",
    phone: "+351 91 345 6789",
    address: "Rua Augusta, 200, 1100-053 Lisboa",
    notes: "Cadeia de 3 restaurantes em Lisboa. IVA mensal. Retenções na fonte sobre rendas.",
    legacy_cliente_id: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 365).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.client4,
    name: "Delta Imobiliária S.A.",
    vat_number: "PT512345678",
    email: "fiscal@deltaimobiliaria.pt",
    phone: "+351 21 234 5678",
    address: "Parque das Nações, Torre Vasco da Gama, 1998-001 Lisboa",
    notes: "Promotora imobiliária. Operações complexas de IVA (inversão sujeito passivo). IUC frota 12 viaturas.",
    legacy_cliente_id: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 200).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
];

// Keep backward compatibility
export const demoClient = demoClients[0];

// ============================================
// CONTACTOS DEMO
// ============================================
export const demoContacts: Contact[] = [
  {
    id: DEMO_IDS.contact1,
    client_id: DEMO_IDS.client1,
    name: "Carlos Mendes",
    role: "Director Financeiro",
    email: "carlos.mendes@alfaindustria.pt",
    phone: "+351 91 234 5678",
    is_primary: true,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 700).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.contact2,
    client_id: DEMO_IDS.client2,
    name: "Sofia Almeida",
    role: "CEO",
    email: "sofia.almeida@betaconsulting.pt",
    phone: "+351 92 345 6789",
    is_primary: true,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 480).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.contact3,
    client_id: DEMO_IDS.client2,
    name: "Rui Martins",
    role: "Controller Financeiro",
    email: "rui.martins@betaconsulting.pt",
    phone: "+351 93 456 7890",
    is_primary: false,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 300).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.contact4,
    client_id: DEMO_IDS.client3,
    name: "António Silva",
    role: "Sócio-Gerente",
    email: "antonio.silva@gamarestauracao.pt",
    phone: "+351 96 789 0123",
    is_primary: true,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 350).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.contact5,
    client_id: DEMO_IDS.client4,
    name: "Mariana Costa",
    role: "Directora Administrativa",
    email: "mariana.costa@deltaimobiliaria.pt",
    phone: "+351 91 012 3456",
    is_primary: true,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 190).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
];

// ============================================
// THREADS DE EMAIL DEMO (5 threads realistas)
// ============================================
export const demoEmailThreads: EmailThread[] = [
  {
    id: DEMO_IDS.thread1,
    account_id: DEMO_IDS.account,
    external_thread_id: "ext-thread-001",
    subject: "Extractos bancários Fevereiro - Alfa Indústria",
    snippet: "Bom dia Ana, junto envio os extractos bancários de Fevereiro conforme solicitado...",
    client_id: DEMO_IDS.client1,
    status: "open",
    importance: "high",
    is_read: false,
    last_message_at: subDays(now, 0).toISOString(),
    message_count: 3,
    snoozed_until: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 2).toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: DEMO_IDS.thread2,
    account_id: DEMO_IDS.account,
    external_thread_id: "ext-thread-002",
    subject: "Re: Recapitulativa 4T 2025 - Beta Consulting",
    snippet: "Agradeço a confirmação dos valores intracomunitários. Procedo à submissão...",
    client_id: DEMO_IDS.client2,
    status: "open",
    importance: "normal",
    is_read: true,
    last_message_at: subDays(now, 1).toISOString(),
    message_count: 4,
    snoozed_until: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 5).toISOString(),
    updated_at: subDays(now, 1).toISOString(),
  },
  {
    id: DEMO_IDS.thread3,
    account_id: DEMO_IDS.account,
    external_thread_id: "ext-thread-003",
    subject: "Retenções na fonte - Gama Restauração",
    snippet: "Boa tarde, precisamos de confirmar os valores das retenções sobre as rendas...",
    client_id: DEMO_IDS.client3,
    status: "open",
    importance: "high",
    is_read: false,
    last_message_at: subDays(now, 0).toISOString(),
    message_count: 2,
    snoozed_until: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 1).toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: DEMO_IDS.thread4,
    account_id: DEMO_IDS.account,
    external_thread_id: "ext-thread-004",
    subject: "Reunião IUC frota - Delta Imobiliária",
    snippet: "Mariana, segue a lista de matrículas para renovação do IUC...",
    client_id: DEMO_IDS.client4,
    status: "snoozed",
    importance: "normal",
    is_read: true,
    last_message_at: subDays(now, 3).toISOString(),
    message_count: 2,
    snoozed_until: addDays(now, 2).toISOString(),
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 7).toISOString(),
    updated_at: subDays(now, 3).toISOString(),
  },
  {
    id: DEMO_IDS.thread5,
    account_id: DEMO_IDS.account,
    external_thread_id: "ext-thread-005",
    subject: "SAF-T Janeiro - ficheiro corrigido",
    snippet: "Segue o ficheiro SAF-T corrigido. O erro estava na série de facturação...",
    client_id: DEMO_IDS.client1,
    status: "open",
    importance: "normal",
    is_read: true,
    last_message_at: subDays(now, 4).toISOString(),
    message_count: 5,
    snoozed_until: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 10).toISOString(),
    updated_at: subDays(now, 4).toISOString(),
  },
];

// ============================================
// MENSAGENS DE EMAIL DEMO
// ============================================
export const demoEmailMessages: Record<string, EmailMessage[]> = {
  [DEMO_IDS.thread1]: [
    {
      id: "demo-msg-001",
      thread_id: DEMO_IDS.thread1,
      external_message_id: "ext-msg-001",
      from_name: "Carlos Mendes",
      from_address: "carlos.mendes@alfaindustria.pt",
      to_addresses: ["ana.rodrigues@acr-contabilidade.pt"],
      cc_addresses: [],
      bcc_addresses: [],
      subject: "Extractos bancários Fevereiro - Alfa Indústria",
      body_html: `<p>Bom dia Ana,</p><p>Junto envio os extractos bancários de Fevereiro conforme solicitado para fecho do IVA.</p><p>Falta ainda o extracto da conta BPI — envio amanhã sem falta.</p><p>Cumprimentos,<br/>Carlos Mendes</p>`,
      body_text: "Bom dia Ana, junto envio os extractos bancários de Fevereiro...",
      attachments: [
        { id: "demo-attach-001", filename: "extracto_CGD_fev2026.pdf", mime_type: "application/pdf", size_bytes: 345600 },
        { id: "demo-attach-002", filename: "extracto_Millennium_fev2026.pdf", mime_type: "application/pdf", size_bytes: 289000 },
      ],
      sent_at: subDays(now, 2).toISOString(),
      direction: "inbound",
      created_at: subDays(now, 2).toISOString(),
    },
    {
      id: "demo-msg-002",
      thread_id: DEMO_IDS.thread1,
      external_message_id: "ext-msg-002",
      from_name: "Ana Rodrigues",
      from_address: "ana.rodrigues@acr-contabilidade.pt",
      to_addresses: ["carlos.mendes@alfaindustria.pt"],
      cc_addresses: [],
      bcc_addresses: [],
      subject: "Re: Extractos bancários Fevereiro - Alfa Indústria",
      body_html: `<p>Carlos,</p><p>Recebi os dois extractos, obrigada. Fico a aguardar o do BPI para fechar o mapa de reconciliação.</p><p>Lembro que o prazo interno para entrega do IVA é dia ${format(addDays(now, 3), "dd/MM")}.</p><p>Cumprimentos,<br/>Ana</p>`,
      body_text: "Recebi os dois extractos, obrigada...",
      attachments: [],
      sent_at: subDays(now, 1).toISOString(),
      direction: "outbound",
      created_at: subDays(now, 1).toISOString(),
    },
    {
      id: "demo-msg-003",
      thread_id: DEMO_IDS.thread1,
      external_message_id: "ext-msg-003",
      from_name: "Carlos Mendes",
      from_address: "carlos.mendes@alfaindustria.pt",
      to_addresses: ["ana.rodrigues@acr-contabilidade.pt"],
      cc_addresses: [],
      bcc_addresses: [],
      subject: "Re: Extractos bancários Fevereiro - Alfa Indústria",
      body_html: `<p>Ana,</p><p>Segue o extracto BPI em anexo. Peço desculpa pelo atraso.</p><p>Carlos</p>`,
      body_text: "Segue o extracto BPI em anexo...",
      attachments: [
        { id: "demo-attach-003", filename: "extracto_BPI_fev2026.pdf", mime_type: "application/pdf", size_bytes: 198000 },
      ],
      sent_at: now.toISOString(),
      direction: "inbound",
      created_at: now.toISOString(),
    },
  ],
  [DEMO_IDS.thread2]: [
    {
      id: "demo-msg-004",
      thread_id: DEMO_IDS.thread2,
      external_message_id: "ext-msg-004",
      from_name: "Rui Martins",
      from_address: "rui.martins@betaconsulting.pt",
      to_addresses: ["ana.rodrigues@acr-contabilidade.pt"],
      cc_addresses: ["sofia.almeida@betaconsulting.pt"],
      bcc_addresses: [],
      subject: "Re: Recapitulativa 4T 2025 - Beta Consulting",
      body_html: `<p>Ana,</p><p>Confirmo os valores das prestações de serviços intracomunitárias do 4T:</p><ul><li>Alemanha: €45.000</li><li>França: €32.500</li><li>Espanha: €18.200</li></ul><p>Cumprimentos,<br/>Rui Martins</p>`,
      body_text: "Confirmo os valores das prestações de serviços intracomunitárias...",
      attachments: [],
      sent_at: subDays(now, 1).toISOString(),
      direction: "inbound",
      created_at: subDays(now, 1).toISOString(),
    },
  ],
  [DEMO_IDS.thread3]: [
    {
      id: "demo-msg-005",
      thread_id: DEMO_IDS.thread3,
      external_message_id: "ext-msg-005",
      from_name: "António Silva",
      from_address: "antonio.silva@gamarestauracao.pt",
      to_addresses: ["ana.rodrigues@acr-contabilidade.pt"],
      cc_addresses: [],
      bcc_addresses: [],
      subject: "Retenções na fonte - Gama Restauração",
      body_html: `<p>Boa tarde Ana,</p><p>Precisamos de confirmar os valores das retenções sobre as rendas dos 3 espaços. Os contratos foram actualizados em Janeiro — junto os novos valores.</p><p>Obrigado,<br/>António</p>`,
      body_text: "Precisamos de confirmar os valores das retenções sobre as rendas...",
      attachments: [
        { id: "demo-attach-004", filename: "contratos_rendas_2026.pdf", mime_type: "application/pdf", size_bytes: 780000 },
      ],
      sent_at: now.toISOString(),
      direction: "inbound",
      created_at: now.toISOString(),
    },
  ],
  [DEMO_IDS.thread4]: [
    {
      id: "demo-msg-006",
      thread_id: DEMO_IDS.thread4,
      external_message_id: "ext-msg-006",
      from_name: "Ana Rodrigues",
      from_address: "ana.rodrigues@acr-contabilidade.pt",
      to_addresses: ["mariana.costa@deltaimobiliaria.pt"],
      cc_addresses: [],
      bcc_addresses: [],
      subject: "Reunião IUC frota - Delta Imobiliária",
      body_html: `<p>Mariana,</p><p>Segue a lista de 12 matrículas cuja renovação do IUC vence nos próximos 30 dias. Precisamos confirmar quais viaturas se mantêm na frota.</p><p>Ana</p>`,
      body_text: "Segue a lista de matrículas cuja renovação do IUC vence...",
      attachments: [],
      sent_at: subDays(now, 3).toISOString(),
      direction: "outbound",
      created_at: subDays(now, 3).toISOString(),
    },
  ],
  [DEMO_IDS.thread5]: [
    {
      id: "demo-msg-007",
      thread_id: DEMO_IDS.thread5,
      external_message_id: "ext-msg-007",
      from_name: "Carlos Mendes",
      from_address: "carlos.mendes@alfaindustria.pt",
      to_addresses: ["ana.rodrigues@acr-contabilidade.pt"],
      cc_addresses: [],
      bcc_addresses: [],
      subject: "SAF-T Janeiro - ficheiro corrigido",
      body_html: `<p>Ana,</p><p>Segue o ficheiro SAF-T corrigido. O erro estava na série de facturação FT-B que não estava a incluir as notas de crédito.</p><p>Carlos</p>`,
      body_text: "Segue o ficheiro SAF-T corrigido...",
      attachments: [
        { id: "demo-attach-005", filename: "SAFT_Jan2026_corrigido.xml", mime_type: "application/xml", size_bytes: 4500000 },
      ],
      sent_at: subDays(now, 4).toISOString(),
      direction: "inbound",
      created_at: subDays(now, 4).toISOString(),
    },
  ],
};

// ============================================
// OBRIGAÇÕES DEMO (15 obrigações distribuídas por 4 clientes)
// ============================================
export const demoObrigacoes = [
  // --- Alfa Indústria ---
  {
    id: DEMO_IDS.obrigacao1,
    titulo: "IVA - Fevereiro 2026",
    tipo: "iva",
    periodicidade: "mensal",
    periodo_referencia: "Fev 2026",
    estado: "pendente",
    deadline_oficial: addDays(now, 7).toISOString(),
    deadline_interna: addDays(now, 3).toISOString(),
    deadline_revisao_senior: addDays(now, 1).toISOString(),
    client_id: DEMO_IDS.client1,
    owner_id: "demo-user-id",
    created_at: subDays(now, 15).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao2,
    titulo: "SAF-T - Janeiro 2026",
    tipo: "saft",
    periodicidade: "mensal",
    periodo_referencia: "Jan 2026",
    estado: "em_revisao",
    deadline_oficial: format(now, "yyyy-MM-dd'T'00:00:00.000'Z'"),
    deadline_interna: subDays(now, 2).toISOString(),
    deadline_revisao_senior: subDays(now, 4).toISOString(),
    client_id: DEMO_IDS.client1,
    owner_id: "demo-user-id",
    created_at: subDays(now, 20).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao3,
    titulo: "DMR - Fevereiro 2026",
    tipo: "dmr",
    periodicidade: "mensal",
    periodo_referencia: "Fev 2026",
    estado: "pendente",
    deadline_oficial: addDays(now, 5).toISOString(),
    deadline_interna: addDays(now, 2).toISOString(),
    deadline_revisao_senior: format(now, "yyyy-MM-dd'T'00:00:00.000'Z'"),
    client_id: DEMO_IDS.client1,
    owner_id: "demo-user-id",
    created_at: subDays(now, 10).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao4,
    titulo: "Modelo 22 - 2025",
    tipo: "modelo_22",
    periodicidade: "anual",
    periodo_referencia: "2025",
    estado: "pendente",
    deadline_oficial: addDays(now, 60).toISOString(),
    deadline_interna: addDays(now, 45).toISOString(),
    deadline_revisao_senior: addDays(now, 30).toISOString(),
    client_id: DEMO_IDS.client1,
    owner_id: "demo-user-id",
    created_at: subDays(now, 5).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },

  // --- Beta Consulting ---
  {
    id: DEMO_IDS.obrigacao5,
    titulo: "IVA - 4º Trimestre 2025",
    tipo: "iva",
    periodicidade: "trimestral",
    periodo_referencia: "4T 2025",
    estado: "atrasado",
    deadline_oficial: subDays(now, 2).toISOString(),
    deadline_interna: subDays(now, 5).toISOString(),
    deadline_revisao_senior: subDays(now, 7).toISOString(),
    client_id: DEMO_IDS.client2,
    owner_id: "demo-user-id",
    created_at: subDays(now, 30).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao6,
    titulo: "Recapitulativa - 4T 2025",
    tipo: "recapitulativa",
    periodicidade: "trimestral",
    periodo_referencia: "4T 2025",
    estado: "em_revisao",
    deadline_oficial: addDays(now, 3).toISOString(),
    deadline_interna: format(now, "yyyy-MM-dd'T'00:00:00.000'Z'"),
    deadline_revisao_senior: subDays(now, 1).toISOString(),
    client_id: DEMO_IDS.client2,
    owner_id: "demo-user-id",
    created_at: subDays(now, 20).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao7,
    titulo: "IES - 2025",
    tipo: "ies",
    periodicidade: "anual",
    periodo_referencia: "2025",
    estado: "pendente",
    deadline_oficial: addDays(now, 90).toISOString(),
    deadline_interna: addDays(now, 75).toISOString(),
    deadline_revisao_senior: addDays(now, 60).toISOString(),
    client_id: DEMO_IDS.client2,
    owner_id: "demo-user-id",
    created_at: subDays(now, 3).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao8,
    titulo: "Modelo 30 - Janeiro 2026",
    tipo: "modelo_30",
    periodicidade: "mensal",
    periodo_referencia: "Jan 2026",
    estado: "submetido",
    deadline_oficial: subDays(now, 5).toISOString(),
    deadline_interna: subDays(now, 8).toISOString(),
    deadline_revisao_senior: subDays(now, 10).toISOString(),
    submetido_em: subDays(now, 6).toISOString(),
    client_id: DEMO_IDS.client2,
    owner_id: "demo-user-id",
    created_at: subDays(now, 25).toISOString(),
    updated_at: subDays(now, 6).toISOString(),
    deleted_at: null,
  },

  // --- Gama Restauração ---
  {
    id: DEMO_IDS.obrigacao9,
    titulo: "IVA - Fevereiro 2026",
    tipo: "iva",
    periodicidade: "mensal",
    periodo_referencia: "Fev 2026",
    estado: "pendente",
    deadline_oficial: addDays(now, 7).toISOString(),
    deadline_interna: addDays(now, 4).toISOString(),
    deadline_revisao_senior: addDays(now, 2).toISOString(),
    client_id: DEMO_IDS.client3,
    owner_id: "demo-user-id",
    created_at: subDays(now, 12).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao10,
    titulo: "Retenções - Fevereiro 2026",
    tipo: "retencoes",
    periodicidade: "mensal",
    periodo_referencia: "Fev 2026",
    estado: "atrasado",
    deadline_oficial: subDays(now, 1).toISOString(),
    deadline_interna: subDays(now, 3).toISOString(),
    deadline_revisao_senior: subDays(now, 5).toISOString(),
    client_id: DEMO_IDS.client3,
    owner_id: "demo-user-id",
    created_at: subDays(now, 15).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao11,
    titulo: "COPE - Janeiro 2026",
    tipo: "cope",
    periodicidade: "mensal",
    periodo_referencia: "Jan 2026",
    estado: "concluido",
    deadline_oficial: subDays(now, 10).toISOString(),
    deadline_interna: subDays(now, 13).toISOString(),
    deadline_revisao_senior: subDays(now, 15).toISOString(),
    concluido_em: subDays(now, 11).toISOString(),
    client_id: DEMO_IDS.client3,
    owner_id: "demo-user-id",
    created_at: subDays(now, 30).toISOString(),
    updated_at: subDays(now, 11).toISOString(),
    deleted_at: null,
  },

  // --- Delta Imobiliária ---
  {
    id: DEMO_IDS.obrigacao12,
    titulo: "IVA - Fevereiro 2026",
    tipo: "iva",
    periodicidade: "mensal",
    periodo_referencia: "Fev 2026",
    estado: "em_revisao",
    deadline_oficial: addDays(now, 7).toISOString(),
    deadline_interna: addDays(now, 3).toISOString(),
    deadline_revisao_senior: format(now, "yyyy-MM-dd'T'00:00:00.000'Z'"),
    client_id: DEMO_IDS.client4,
    owner_id: "demo-user-id",
    created_at: subDays(now, 14).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao13,
    titulo: "IUC - Renovação frota",
    tipo: "iuc",
    periodicidade: "anual",
    periodo_referencia: "2026",
    estado: "pendente",
    deadline_oficial: addDays(now, 14).toISOString(),
    deadline_interna: addDays(now, 7).toISOString(),
    deadline_revisao_senior: addDays(now, 5).toISOString(),
    client_id: DEMO_IDS.client4,
    owner_id: "demo-user-id",
    created_at: subDays(now, 7).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao14,
    titulo: "DMIS - 4T 2025",
    tipo: "dmis",
    periodicidade: "trimestral",
    periodo_referencia: "4T 2025",
    estado: "aprovado",
    deadline_oficial: addDays(now, 1).toISOString(),
    deadline_interna: subDays(now, 1).toISOString(),
    deadline_revisao_senior: subDays(now, 3).toISOString(),
    aprovado_em: subDays(now, 0).toISOString(),
    client_id: DEMO_IDS.client4,
    owner_id: "demo-user-id",
    created_at: subDays(now, 25).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
  {
    id: DEMO_IDS.obrigacao15,
    titulo: "Retenções - Fevereiro 2026",
    tipo: "retencoes",
    periodicidade: "mensal",
    periodo_referencia: "Fev 2026",
    estado: "pendente",
    deadline_oficial: addDays(now, 5).toISOString(),
    deadline_interna: addDays(now, 2).toISOString(),
    deadline_revisao_senior: format(now, "yyyy-MM-dd'T'00:00:00.000'Z'"),
    client_id: DEMO_IDS.client4,
    owner_id: "demo-user-id",
    created_at: subDays(now, 8).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
  },
];

// ============================================
// TAREFAS DEMO (10 tarefas distribuídas)
// ============================================
export const demoTasks: TaskWithRelations[] = [
  // Alfa Indústria
  {
    id: DEMO_IDS.task1,
    title: "Reconciliar extractos bancários Alfa Indústria",
    description: "Reconciliar os 3 extractos (CGD, Millennium, BPI) de Fevereiro para fecho do IVA",
    client_id: DEMO_IDS.client1,
    linked_email_thread_id: DEMO_IDS.thread1,
    status: "in_progress",
    priority: "high",
    due_date: format(now, "yyyy-MM-dd"),
    assignee_id: "demo-user-id",
    completed_at: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 3).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client1, name: "Alfa Indústria Lda" },
    email_thread: { id: DEMO_IDS.thread1, subject: "Extractos bancários Fevereiro - Alfa Indústria" },
  },
  {
    id: DEMO_IDS.task2,
    title: "Validar SAF-T Janeiro corrigido",
    description: "Verificar se o ficheiro SAF-T corrigido passa na validação da AT",
    client_id: DEMO_IDS.client1,
    linked_email_thread_id: DEMO_IDS.thread5,
    status: "todo",
    priority: "high",
    due_date: subDays(now, 1).toISOString().split("T")[0],
    assignee_id: "demo-user-id",
    completed_at: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 5).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client1, name: "Alfa Indústria Lda" },
    email_thread: { id: DEMO_IDS.thread5, subject: "SAF-T Janeiro - ficheiro corrigido" },
  },
  // Beta Consulting
  {
    id: DEMO_IDS.task3,
    title: "Submeter IVA 4T Beta Consulting (URGENTE)",
    description: "IVA em atraso — submeter imediatamente na AT",
    client_id: DEMO_IDS.client2,
    linked_email_thread_id: null,
    status: "todo",
    priority: "high",
    due_date: subDays(now, 2).toISOString().split("T")[0],
    assignee_id: "demo-user-id",
    completed_at: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 4).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client2, name: "Beta Consulting S.A." },
    email_thread: null,
  },
  {
    id: DEMO_IDS.task4,
    title: "Preparar Recapitulativa 4T Beta",
    description: "Valores intracomunitários confirmados por Rui Martins. Preencher declaração.",
    client_id: DEMO_IDS.client2,
    linked_email_thread_id: DEMO_IDS.thread2,
    status: "in_progress",
    priority: "medium",
    due_date: format(now, "yyyy-MM-dd"),
    assignee_id: "demo-user-id",
    completed_at: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 2).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client2, name: "Beta Consulting S.A." },
    email_thread: { id: DEMO_IDS.thread2, subject: "Re: Recapitulativa 4T 2025 - Beta Consulting" },
  },
  // Gama Restauração
  {
    id: DEMO_IDS.task5,
    title: "Confirmar valores retenções rendas Gama",
    description: "Contratos actualizados em Janeiro. Verificar novos valores de retenção.",
    client_id: DEMO_IDS.client3,
    linked_email_thread_id: DEMO_IDS.thread3,
    status: "todo",
    priority: "high",
    due_date: format(now, "yyyy-MM-dd"),
    assignee_id: "demo-user-id",
    completed_at: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 1).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client3, name: "Gama Restauração Unip. Lda" },
    email_thread: { id: DEMO_IDS.thread3, subject: "Retenções na fonte - Gama Restauração" },
  },
  {
    id: DEMO_IDS.task6,
    title: "Lançar facturas fornecedores Gama",
    description: "Lançar facturas de fornecedores de Fevereiro para cálculo do IVA",
    client_id: DEMO_IDS.client3,
    linked_email_thread_id: null,
    status: "todo",
    priority: "medium",
    due_date: addDays(now, 2).toISOString().split("T")[0],
    assignee_id: "demo-user-id",
    completed_at: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 3).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client3, name: "Gama Restauração Unip. Lda" },
    email_thread: null,
  },
  // Delta Imobiliária
  {
    id: DEMO_IDS.task7,
    title: "Levantar lista matrículas IUC Delta",
    description: "Confirmar com Mariana Costa quais viaturas se mantêm na frota para renovação IUC",
    client_id: DEMO_IDS.client4,
    linked_email_thread_id: DEMO_IDS.thread4,
    status: "todo",
    priority: "medium",
    due_date: addDays(now, 5).toISOString().split("T")[0],
    assignee_id: "demo-user-id",
    completed_at: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 3).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client4, name: "Delta Imobiliária S.A." },
    email_thread: { id: DEMO_IDS.thread4, subject: "Reunião IUC frota - Delta Imobiliária" },
  },
  {
    id: DEMO_IDS.task8,
    title: "Submeter DMIS 4T Delta",
    description: "DMIS aprovado. Proceder à submissão na AT.",
    client_id: DEMO_IDS.client4,
    linked_email_thread_id: null,
    status: "todo",
    priority: "high",
    due_date: addDays(now, 1).toISOString().split("T")[0],
    assignee_id: "demo-user-id",
    completed_at: null,
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 1).toISOString(),
    updated_at: now.toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client4, name: "Delta Imobiliária S.A." },
    email_thread: null,
  },
  // Completed tasks
  {
    id: DEMO_IDS.task9,
    title: "Submeter Modelo 30 Janeiro Beta",
    description: "Modelo 30 submetido com sucesso na AT",
    client_id: DEMO_IDS.client2,
    linked_email_thread_id: null,
    status: "done",
    priority: "high",
    due_date: subDays(now, 6).toISOString().split("T")[0],
    assignee_id: "demo-user-id",
    completed_at: subDays(now, 6).toISOString(),
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 12).toISOString(),
    updated_at: subDays(now, 6).toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client2, name: "Beta Consulting S.A." },
    email_thread: null,
  },
  {
    id: DEMO_IDS.task10,
    title: "Fechar COPE Janeiro Gama",
    description: "COPE entregue e validado",
    client_id: DEMO_IDS.client3,
    linked_email_thread_id: null,
    status: "done",
    priority: "medium",
    due_date: subDays(now, 11).toISOString().split("T")[0],
    assignee_id: "demo-user-id",
    completed_at: subDays(now, 11).toISOString(),
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 20).toISOString(),
    updated_at: subDays(now, 11).toISOString(),
    deleted_at: null,
    client: { id: DEMO_IDS.client3, name: "Gama Restauração Unip. Lda" },
    email_thread: null,
  },
];

// ============================================
// WORK ITEM LINKS DEMO
// ============================================
export const demoWorkItemLinks: WorkItemLink[] = [
  {
    id: DEMO_IDS.workItemLink1,
    external_table: "obrigacoes",
    external_id: DEMO_IDS.obrigacao1,
    client_id: DEMO_IDS.client1,
    thread_id: DEMO_IDS.thread1,
    task_id: DEMO_IDS.task1,
    link_type: "related",
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 3).toISOString(),
  },
  {
    id: DEMO_IDS.workItemLink2,
    external_table: "obrigacoes",
    external_id: DEMO_IDS.obrigacao6,
    client_id: DEMO_IDS.client2,
    thread_id: DEMO_IDS.thread2,
    task_id: DEMO_IDS.task4,
    link_type: "related",
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 2).toISOString(),
  },
  {
    id: DEMO_IDS.workItemLink3,
    external_table: "obrigacoes",
    external_id: DEMO_IDS.obrigacao10,
    client_id: DEMO_IDS.client3,
    thread_id: DEMO_IDS.thread3,
    task_id: DEMO_IDS.task5,
    link_type: "related",
    owner_id: "demo-user-id",
    tenant_id: "demo-user-id",
    created_at: subDays(now, 1).toISOString(),
  },
];

// ============================================
// ACTIVITY LOG DEMO
// ============================================
export const demoActivityLog: ActivityLogEntry[] = [
  {
    id: "demo-activity-001",
    actor_id: "demo-user-id",
    action: "created",
    entity_type: "task",
    entity_id: DEMO_IDS.task1,
    metadata: { task_title: "Reconciliar extractos bancários Alfa Indústria" },
    tenant_id: "demo-user-id",
    created_at: subDays(now, 3).toISOString(),
  },
  {
    id: "demo-activity-002",
    actor_id: "demo-user-id",
    action: "email_received",
    entity_type: "email_thread",
    entity_id: DEMO_IDS.thread1,
    metadata: { subject: "Extractos bancários Fevereiro - Alfa Indústria" },
    tenant_id: "demo-user-id",
    created_at: subDays(now, 2).toISOString(),
  },
  {
    id: "demo-activity-003",
    actor_id: "demo-user-id",
    action: "status_updated",
    entity_type: "obrigacao",
    entity_id: DEMO_IDS.obrigacao5,
    metadata: { old_status: "pendente", new_status: "atrasado", titulo: "IVA 4T Beta Consulting" },
    tenant_id: "demo-user-id",
    created_at: subDays(now, 1).toISOString(),
  },
  {
    id: "demo-activity-004",
    actor_id: "demo-user-id",
    action: "completed",
    entity_type: "task",
    entity_id: DEMO_IDS.task9,
    metadata: { task_title: "Submeter Modelo 30 Janeiro Beta" },
    tenant_id: "demo-user-id",
    created_at: subDays(now, 6).toISOString(),
  },
  {
    id: "demo-activity-005",
    actor_id: "demo-user-id",
    action: "linked_to_client",
    entity_type: "email_thread",
    entity_id: DEMO_IDS.thread3,
    metadata: { client_name: "Gama Restauração Unip. Lda" },
    tenant_id: "demo-user-id",
    created_at: now.toISOString(),
  },
];

// ============================================
// COMMENTS DEMO
// ============================================
export const demoComments: Comment[] = [
  {
    id: "demo-comment-001",
    entity_type: "task",
    entity_id: DEMO_IDS.task3,
    author_id: "demo-user-id",
    body: "IVA 4T da Beta em atraso! Falta apenas confirmação dos valores de dedução. Submeter hoje sem falta.",
    mentions: [],
    is_internal: true,
    created_at: subDays(now, 1).toISOString(),
    updated_at: subDays(now, 1).toISOString(),
  },
  {
    id: "demo-comment-002",
    entity_type: "email_thread",
    entity_id: DEMO_IDS.thread3,
    author_id: "demo-user-id",
    body: "Cliente enviou novos contratos de renda. Valores de retenção alterados — verificar antes de submeter.",
    mentions: [],
    is_internal: true,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
];

// ============================================
// DOCUMENTOS DEMO
// ============================================
export const demoDocuments = [
  {
    id: "demo-doc-001",
    client_id: DEMO_IDS.client1,
    file_name: "Contrato_AlfaIndustria_2026.pdf",
    file_type: "contract",
    mime_type: "application/pdf",
    size_bytes: 1024000,
    storage_key: "demo/contrato_alfa_2026.pdf",
    is_proof: false,
    uploaded_by: "demo-user-id",
    tenant_id: "demo-user-id",
    uploaded_at: subDays(now, 60).toISOString(),
  },
  {
    id: "demo-doc-002",
    client_id: DEMO_IDS.client2,
    file_name: "Comprovativo_Modelo30_Jan2026.pdf",
    file_type: "proof",
    mime_type: "application/pdf",
    size_bytes: 256000,
    storage_key: "demo/comprovativo_m30_jan.pdf",
    is_proof: true,
    uploaded_by: "demo-user-id",
    tenant_id: "demo-user-id",
    uploaded_at: subDays(now, 6).toISOString(),
  },
  {
    id: "demo-doc-003",
    client_id: DEMO_IDS.client3,
    file_name: "Comprovativo_COPE_Jan2026.pdf",
    file_type: "proof",
    mime_type: "application/pdf",
    size_bytes: 180000,
    storage_key: "demo/comprovativo_cope_jan.pdf",
    is_proof: true,
    uploaded_by: "demo-user-id",
    tenant_id: "demo-user-id",
    uploaded_at: subDays(now, 11).toISOString(),
  },
];

// ============================================
// FUNÇÃO DE VERIFICAÇÃO E TOGGLE
// ============================================
const DEMO_MODE_KEY = "demo-mode-enabled";

export function isDemoMode(): boolean {
  // Check localStorage first, then env var
  const localStorageValue = localStorage.getItem(DEMO_MODE_KEY);
  if (localStorageValue !== null) {
    return localStorageValue === "true";
  }
  return import.meta.env.VITE_SEED_ENABLED === "true";
}

export function enableDemoMode(): void {
  localStorage.setItem(DEMO_MODE_KEY, "true");
}

export function disableDemoMode(): void {
  localStorage.setItem(DEMO_MODE_KEY, "false");
}

export function toggleDemoMode(): boolean {
  const newValue = !isDemoMode();
  localStorage.setItem(DEMO_MODE_KEY, String(newValue));
  return newValue;
}

// ============================================
// EXPORT IDS PARA USO EXTERNO
// ============================================
export { DEMO_IDS };
