project_id = "llxyacgxypfmvwkrtdte"

[functions.google-oauth]
verify_jwt = true

[functions.gmail-sync]
verify_jwt = true

[functions.sync-gmail-cron]
verify_jwt = false

[functions.healthz]
verify_jwt = false

[functions.backfill-reminders]
verify_jwt = true

[functions.calculate-reminders]
verify_jwt = true

[functions.dispatch-reminders]
verify_jwt = true
